
local OlympusEnemyData = ModUtil.Entangled.ModData(EnemyData)
local OlympusUnitSetData = ModUtil.Entangled.ModData(UnitSetData) --.Enemies
local OlympusDeathLoopData = ModUtil.Entangled.ModData(DeathLoopData)

GiftData.NPC_Theseus_01 = {
		Gift = true,
		InheritFrom = {"DefaultGiftData"},
		MaxedIcon = "Keepsake_Theseus_Max",
		MaxedSticker = "Keepsake_TheseusSticker_Max",
		MaxedRequirement = { RequiredTextLines = { "TheseusGift08" } },
		Locked = 7,
		Maximum = 8,
		[7] = { RequiredResource = "SuperGiftPoints" },
		[8] = { RequiredResource = "SuperGiftPoints" },
		UnlockGameStateRequirements = { RequiredTextLines = { "TheseusInsecurityQuest05"} }
}

table.insert( GameData.ConversationOrder,
    "NPC_Theseus_01"
)

function orderGifts()
	GiftOrderingReverseLookup = {}
	for index, name in pairs(GiftOrdering) do
		GiftOrderingReverseLookup[name] = index
	end
end

ModUtil.LoadOnce(orderGifts())
table.insert(OlympusDeathLoopData.DeathArea.StartUnthreadedEvents, {
	FunctionName = "ActivateRotatingNPCs",
	GameStateRequirements =
	{
		RequiredFalseFlags = { "InFlashback" },
	},
	Args =
	{
		Types =
		{
			"NPC_Theseus_01",
		},
		ActivationCapMin = 1,
		ActivationCapMax = 1,
		SkipPresentation = true,
	},
})
OlympusEnemyData.NPC_Theseus_01 =

	{
		-- Theseus, Id = 1000001 
		Name = "NPC_Theseus_01",
		InheritFrom = { "NPC_Neutral", "NPC_Giftable" },
		UseText = "UseTalkToThanatos",
		Portrait = "Portrait_Theseus_Default_01",
		AnimOffsetZ = 220,
		EmoteOffsetX = -50,
		EmoteOffsetY = -250,
		Groups = { "NPCs" },
		--GenusName = "Theseus",
		SkipInitialGiftRequirement = true,
		CanReceiveGift = true,


		Binks = 
		{
			"TheseusIdle_Bink",
			"TheseusTaunt_Bink",
		},

		SubtitleColor = Color.TheseusVoice,

		ActivateRequirements =
		{
			RequiredAnyTextLines = { "TheseusFirstAppearance_NotMetMinotaur", "TheseusFirstAppearance_MetBeatMinotaur", "TheseusFirstAppearance_MetNotBeatMinotaur" },
		},

		InteractTextLineSets =
		{

			TheseusFirstMeeting =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusFirstMeeting",
				SuperPriority = true,
				PlayOnce = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				InitialGiftableOffSource = true,
				UseInitialInteractSetup = true,
				RequiredAnyTextLines = { "TheseusFirstAppearance_NotMetMinotaur", "TheseusFirstAppearance_MetBeatMinotaur", "TheseusFirstAppearance_MetNotBeatMinotaur" },

				{ PreLineWait = 0.35, AngleTowardHero = true,
					Text = "What are you doing here, blackguard? You don't deserve to step foot near this entrance to Elysium's most glorious stadium." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "How else did you think I got in? And I'm buying supplies to help me escape this place. What are you doing here, anyway? Never seen you outside the stadium before." },
				{ Text = "I'm a frequent patron of Charon's wares and was purchasing some goods that will aid me in vanquishing you. All for the benefit of our audience, of course! I could destroy you with my bare hands if I wished." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "You need the help of both Asterius and the gods to have a chance at destroying me, but you can believe otherwise if it makes you feel better." },
				{ Emote = "PortraitEmoteAnger", Text = "You lie, blackguard! You'll see just how powerful I am soon, you foul pustule!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "You mean I'll see how powerful you and Asterius and the gods are? I look forward to it. See you soon!" },
			},
			TheseusSecondMeeting =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusSecondMeeting",
				SuperPriority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredRunsCleared = 0,
				RequiredKills = {Theseus = 0},
				RequiredTextLines = { "TheseusFirstMeeting" },
				{ PreLineWait = 0.35, AngleTowardHero = true, 
					Text = "Prepare yourself for an epic battle, blackguard! " },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					PreLineAnim = "ZagreusTalkEmpathyStart", PreLineAnimTarget = "Hero",
					PostLineAnim = "ZagreusTalkEmpathy_Return", PostLineAnimTarget = "Hero",
					Text = "Aww, did you really wait for me outside the stadium again just to tell me that? How sweet!" },
				{ Text = "Your wicked words can't hurt me! Not like my spear will when it soon eviscerates you. Prepare for your imminent death once you step through those doors!" },
			},

			
			TheseusSecondMeetingAlt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusSecondMeetingAlt",
				SuperPriority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredFalseTextLines = { "TheseusSecondMeeting" },
				RequiredTextLines = { "TheseusFirstMeeting" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Why have you returned to us again, daemon?" },
				{ Portrait = "Portrait_Zag_Serious_01", Speaker = "CharProtag",
					Text = "I just couldn't resist the urge to kill you once more, Theseus." },
				{ Text = "Foul lies! Your wicked words won't fool me! Prepare for your imminent death once you step through those doors." },
			},
			
			TheseusInsecurityQuest01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusInsecurityQuest01",
				Priority = true,
				PlayOnce = true,
				RequiredTextLines = { "AsteriusInsecurityQuest01" },
				RequiredKills = { Theseus = 10 },
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Good day or night, Theseus. How are you?" },
				{ AngleTowardHero = true, Emote = "PortraitEmoteDepressed", Text = "Prince Zagreus. Come to slay me yet again in front of all the other shades of Elysium?" },
				{ Portrait = "Portrait_Zag_Serious_01", Speaker = "CharProtag",
					Text = "So, not good then. Theseus, no one thinks less of you if you lose. Is that what you worry about? Losing the respect of the other shades here?" },
				{ Text = "How could I not? I'd estimate that you've slain me around ten times by now, if not more. What kind of warrior am I?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "You're a Champion, that's who. I'm just getting stronger, but you're still a worthy opponent." },
				{ Text = "That's a meaningless consolation, daemon." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Zagreus. And it's not meaningless. However, there's more to life than just fighting all the time." },
				{ Text = "This is Elysium. The greatest warriors are here, and they want to spend an eternity fighting." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Is that what you want? Is there nothing else you'd rather be doing?" },
				{ Text = "Fighting's all I've ever known, so no. There's nothing else like the rush of battle." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I'm going to find you a hobby." },
				{ Text = "You can try. In the meantime, arm yourself! Another fight is close at hand." },
			},

			TheseusInsecurityQuest02 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusInsecurityQuest02",
				Priority = true,
				PlayOnce = true,
				RequiredTextLines = { "TheseusInsecurityQuest01" },
				RequiredMinRunsCleared = 3,
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Fair tidings to you, Prince Zagreus. I believe I've found myself a hobby!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Oh really? What is it?" },
				{ Text = "I spent some time nurturing the gardens of Elysium. It was strangely relaxing." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Ah, my mother loves gardening! See, it gave you something positive to do that didn't involve killing anyone. Not that I can really talk." },
				{ Text = "It did feel comforting, for some reason. But how will it help me? Gardening won't gain the respect of the shades here." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "No, but I'd like you to see that you don't need their respect. If you stopped caring so much about what everyone else thought of you, you'd be happier." },
				{ Text = "Outrageous. Like I said, this is all I've known during my life and death. I honestly don't know how I'd stop caring." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "We'll keep working on it." },
			},
			TheseusInsecurityQuest03 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusInsecurityQuest03",
				Priority = true,
				PlayOnce = true,
				RequiredTextLines = { "AsteriusInsecurityQuest02" },
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Hey Theseus. How's the gardening going?" },
				{ AngleTowardHero = true, Text = "Wonderfully! I've helped make the splendors of Elysium even more brilliant. It's been good to contribute something other than bloodshed to the realm." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I was hoping that would be the case." },
				{ Text = "But I still don't understand the purpose of doing this. Am I not still the Champion? How will this aid me?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I wanted to talk about that, actually. I think your troubles stem from your need for others to look up to you. You should be comfortable with yourself rather than relying on respect from others." },
				{ Text = "That's easier said than done." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "True. But Asterius cares for you. So do I. The opinions of the other shades don't matter. Next time you have a negative thought about yourself, remember that." },
				{ Text = "Hm. I'll try, but I may be too set in my phantasmagoric ways to change." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "I don't think that's true." },
			},
			TheseusInsecurityQuest04 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusInsecurityQuest04",
				Priority = true,
				PlayOnce = true,
				RequiredMinCompletedRuns = 20,
				RequiredTextLines = { "TheseusInsecurityQuest03" },
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "You look happy today, Theseus." },
				{ AngleTowardHero = true, Emote = "PortraitEmoteCheerful", Text = "Prince Zagreus! I am. I've been practicing what you've suggested, and it has seemed to make a difference." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "That's wonderful news!" },
				{ Text = "A shade insulted me earlier this day or night. Rather than shouting at them, I thought about what Asterius would say. He wouldn't let it bother him, so neither did I." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "That's great to hear, honestly. It sounds like you've made a lot of progress." },
				{ Text = "I have. Just you wait - I'll be more skilled at thinking positively soon than anyone else in Elysium!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I bet you will." },
			},
			TheseusInsecurityQuest05 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusInsecurityQuest05",
				Priority = true,
				PlayOnce = true,
				RequiredMinCompletedRuns = 30,
				RequiredTextLines = { "TheseusInsecurityQuest04" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Emote = "PortraitEmoteCheerful", Text = "Good day or night to you, Prince Zagreus!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Hey Theseus. Still doing well?" },
				{ Text = "I am. I've realized that I don't have to be the best at thinking positively. This is no competition. I just need to keep working on it." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Exactly. I really think you're getting there." },
				{ Text = "I've even continued with my gardening. Thank you for your support, friend! With dear friends like you and Asterius, I need no one else." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I'm glad to call you a friend as well, Theseus." },
			},
			TheseusRomanceQuest01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusRomanceQuest01",
				Priority = true,
				PlayOnce = true,
				RequiredTextLines = { "AsteriusRomanceQuest02", "TheseusGift06" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Fair tidings to you on this lovely day or night in Elysium, Prince!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Same to you, Theseus. I had a question for you, actually." },
				{ Text = "How may I assist you?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I was wondering how you'd feel about me bedding Asterius." },
				{ Emote = "PortraitEmoteSurprise", Text = "About you {#DialogueItalicFormat}what{#PreviousFormat}? Making love to the bull? Absolutely not!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Wait, why not? You don't hold any sort of claim to him, do you?" },
				{ Text = "Pfft... I mean! ...Well, no, I suppose I don't. But please, don't bed him. Does he want you to?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Perhaps. Maybe I haven't asked him yet and wanted to get your opinion first." },
				{ Text = "If so, then please don't ask him. I know he's handsome, but he's my dearest companion, and we share a bond." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Understood. I'll keep my thoughts to myself then." },
			},
			TheseusRomanceQuest02 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusRomanceQuest02",
				Priority = true,
				PlayOnce = true,
				RequiredTextLines = { "AsteriusRomanceQuest03", "TheseusGift06" },
				MinRunsSinceAnyTextLines = { TextLines = { "AsteriusRomanceQuest03" }, Count = 3 },
				{ PreLineWait = 0.35, AngleTowardHero = true, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus, just out of curiosity, has Asterius said anything interesting about your relationship recently?" },
				{ Text = "Hm? No, not that I'm aware of. But everything my dear Asterius has to say is always interesting!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Guess he hasn't asked yet then." },
				{ Text = "What was that?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Nothing! Just looking forward to our match." },
			},
			TheseusRomanceQuest03 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusRomanceQuest03",
				SuperPriority = true,
				PlayOnce = true,
				RequiredTextLines = { "AsteriusRomanceQuest04", "TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Prince, I wanted to speak with you!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "What is it, Theseus?" },
				{ Text = "Perchance, when you enquired previously into whether or not Asterius had spoken to me about our relationship, were you referencing his declaration of his feelings?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Yes, but he hadn't asked you yet." },
				{ Text = "Well, he did now! And we celebrated by exploring each other gloriously!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I'm very glad to hear that it worked out! Please don't feel the need to tell me every detail." },
				{ Text = "There's so much to share, though! Oh, it was amazing." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Good to know!" },
			},
			TheseusBackstory01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusBackstory01",
				Priority = true,
				PlayOnce = true,
				GiftableOffSource = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Have I ever told you about my life in Athens, blackguard? The tales are glorious enough that even ears as foul as yours deserve to hear them." },
				{  Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag", 
					Text = "You've never told me, nor have I ever been interested." },
				{ Emote = "PortraitEmoteAnger", Text = "Cruel daemon! I offered to share my history with you, my life, and you refuse?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "You got it. Maybe if you were nicer to me, I'd feel like humoring your nostalgia." },
				{ Text = "Nicer! {#DialogueItalicFormat}Pah! {#PreviousFormat} There's no one in all of Elysium as nice as me." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "You keep telling yourself that. In the meantime, I'll spend my time with those aforementioned nicer shades." },
			},
			TheseusBackstory02 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusBackstory02",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusGift06" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Prince Zagreus, would you care to hear stories of my life in Athens? While they may pale in comparison to the stories of the Underworld, you may find them intriguing." },
				{  Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", 
					Text = "I'd love to hear your stories. Life in the Underworld feels so distant from the surface, sometimes." },
				{ PostLineThreadedFunctionName = "LoungeRevelryPresentation", PostLineFunctionArgs = { Sound2 = "/EmptyCue", Sound3 = "/EmptyCue" }, Text = "I'd love nothing more than to share them! And to share a drink with you! Would you perchance join me?"},

				{ FadeOutTime = 0.5, FullFadeTime = 7.8, FadeInTime = 2.0, InterSceneWaitTime = 0.5, Text = "And so poor Asterius fell, and I escaped the labyrinth."},
				
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Your stories are fascinating, even in comparison to those of the Underworld." },
				{ Text = "I have many more to share!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I'd love to hear them sometime." },
			},

			TheseusKeepsake01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusKeepsake01",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				GiftableOffSource = true,
				UseableOffSource = true,
				RequiredFalseTextLines = {"TheseusGift06", "TheseusKeepsake01Alt"},
				RequiredTrait = "GodsFavorTrait",
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Blackguard, do I spot one of my beautiful golden cuffs on your wrist? How dare you wear that!" },
				{  Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag", 
					Text = "What? You gave it to me? Did you not want me to wear it?" },
				{ Emote = "PortraitEmoteAnger", Text = "Be glad we're not in the stadium now, or I would disembowel you for spouting such ridiculous lies! I would never give you any of my many prized possessions." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "We can pretend like you didn't gift it to me if you'd like, but I'm not going to stop wearing it. It's quite useful having the gods favor me even more." },
				{ Text = "The gods would never favor you, daemon! You'll see soon when I call upon them and smite you!" },
			},
			TheseusKeepsake01Alt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusKeepsake01Alt",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = {"TheseusGift08"},
				RequriedFalseTextLines = {"TheseusKeepsake01"},
				RequiredTrait = "GodsFavorTrait",
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Prince Zagreus, what is that splendid cuff you're wearing on your wrist?" },
				{  Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", 
					Text = "Oh, this? It's the keepsake you gave me. It's been quite useful having Olympus favor me even more." },
				{ Text = "What glorious news! My old equipment is being used by a god! Dear friend, you have truly made my day or night." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I'm glad. Seriously, thanks for giving me this." },
				{ Text = "It's the least I can do for you considering all that you've done for me! Now, what do you say we battle to the death in front of our loving audience?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I'd say that sounds like an excellent idea." },
			},

			TheseusAboutAriadne01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutAriadne01",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredAnyTextLines = { "TheseusYarnReaction04", "TheseusYarnReaction04_B" },
				RequiredTrait = "TemporaryBoonRarityTrait",
				RequiredFalseTextLines = {"TheseusGift06", "TheseusAboutAriadne01Alt"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Why do you yet again carry around that ball of yarn, daemon? Haven't I told you it bothers me?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I've gotten that impression, but I can't say bothering you bothers me. Who was Ariadne to you, anyway?" },
				{ Text = "Why do you care, fiend? She's no one, now. She's of no more significance than a speck of dust compared to me! She's just another shade somewhere in the Underworld." },
			},
			TheseusAboutAriadne01Alt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutAriadne01Alt",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredAnyTextLines = { "TheseusYarnReaction04", "TheseusYarnReaction04_B" },
				RequiredTrait = "TemporaryBoonRarityTrait",
				RequiredTextLines = {"TheseusGift06"},
				RequiredFalseTextLines = {"TheseusAboutAriadne01"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Why do you yet again carry around that ball of yarn, my dear friend? Haven't I told you it bothers me?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I'm sorry. It helps me find better boons from the gods, but I forgot that it bothered you. Who was Ariadne to you, anyway?" },
				{ Text = "She's no one, now. Just another shade somewhere in the Underworld." },
			},

			TheseusAboutAriadne02 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutAriadne02",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredAnyTextLines = { "TheseusAboutAriadne01", "TheseusAboutAriadne01Alt" },
				RequiredAnyTextLines = {"TheseusYarnReaction04", "TheseusYarnReaction04_B"},
				RequiredFalseTextLines = {"TheseusGift06", "TheseusAboutAriadne02Alt"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I tried to look for Ariadne, but couldn't find her." },
				{ AngleTowardHero = true, Text = "You interfering, loathsome, ungracious pustule! Why would you search for her?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Well, you wouldn't tell me who she was, so I thought I'd figure it out for myself. But I haven't had any luck." },
				{ Text = "I abandoned her, foolish blackguard! Left her on an island to die because I didn't return her affections. So despite what I told Asterius, I have no desire to find her." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I wouldn't want anything to do with you either if I was her. Maybe I'll let her rest in peace, then." },			
			},
			TheseusAboutAriadne02Alt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutAriadne02Alt",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredAnyTextLines = { "TheseusAboutAriadne01", "TheseusAboutAriadne01Alt" },
				RequiredAnyTextLines = {"TheseusYarnReaction04", "TheseusYarnReaction04_B"},
				RequiredTextLines = {"TheseusGift06"},
				RequiredFalseTextLines = {"TheseusAboutAriadne02"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I tried to look for Ariadne for you, but couldn't find her." },
				{ AngleTowardHero = true, Text = "You'd do that for me? Why would you search for her?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Well, you said you'd seek her out, so I thought I'd help out. But I haven't had any luck." },
				{ Text = "She wouldn't want to see me anyways. I abandoned her, Prince! Left her on an island to die because I didn't return her affections. So despite what I told Asterius, I have no desire to find her." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Oh wow. Maybe you're better off not finding her, then." },			
			},

			TheseusAboutAriadne03 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutAriadne03",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredAnyTextLines = { "TheseusAboutAriadne02", "TheseusAboutAriadne02Alt", "AsteriusAboutAriadne03"},
				RequiredTextLines = {"TheseusGift08"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Serious_01", Speaker = "CharProtag",
					Text = "Theseus, I think I found Ariadne." },
				{ AngleTowardHero = true, Text = "What? You were still searching for her?"},
				{ Portrait = "Portrait_Zag_Serious_01", Speaker = "CharProtag",
					Text = "I was. She's Asterius's sister, and I owe it to him. She's to the northwest of here in an Elysium cottage." },
				{ Text = "Daemon -- I mean Prince -- I don't know what to say for once. Or what to do, for that matter. You're a god. Should I seek her out?" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "I can't tell you what to do. Follow your conscience, Theseus. I just wanted to tell you where she was." },
				{ Text = "Thank you. I... I need some time to myself for a moment. Don't worry, I'll still meet you on the battlefield."},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Good luck, king." },
			},

			TheseusAboutHades =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutHades",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = {"TheseusGift07"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Hey Theseus. How's Elysium holding up?" },
				{ AngleTowardHero = true, Text = "Greetings, my dear friend! We're still working on the repairs from your last visit, but everything's nearly fixed."},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "That's good! I'm sorry if I cause a lot of work for you. I guess I don't really think about the actual clean up involved with destroying a realm." },
				{ Text = "Why, I once slew Asterius in his labyrinth! Some repair work is naught but a trifle in comparison. And it keeps your father satisfied with us!" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "Does he get frustrated with you when you lose to me?" },
				{ Text = "Occasionally. He comes up here on his way to the surface and speaks with Asterius and I. He's rarely pleased with us. But it's nothing my compatriot and I can't handle!"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Well, if you ever need me to have a word with him, just let me know." },
			},

			TheseusAboutThan =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutThan",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredAnyTextLines = { "BecameCloseWithThanatos01Than_GoToHim", "BecameCloseWithThanatos01_BThan_GoToHim" },
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Blackguard, a most foul rumor has been circulating. Supposedly you've begun a relationship with the god of death himself?"},
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Than? Yeah, we're dating, not that it's any of your business." },
				{ Text = "You've bestowed a nickname upon the god of death? Given that we face each other in figuratively mortal combat regularly, how would this not be my business?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "It's not like he's going to help me defeat you. Well, unless I ask him to. Maybe you should worry." },
				{ Text = "I absolutely should. Although I have no doubt my dear Asterius and I can take on Death with ease!"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I highly doubt that. I guess we'll see!" },
			},
			TheseusAboutMeg =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutMeg",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredAnyTextLines = { "BecameCloseWithMegaera01_BMeg_GoToHer", "BecameCloseWithMegaera01Meg_GoToHer" },
				RequiredFalseTextLines = {"TheseusGift06", "AsteriusRomanceQuest05"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Blackguard, you're consorting with a fury?"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Who, Meg? Possibly. We used to be together so this isn't a new thing." },
				{ Text = "You have even poorer judgement than I expected, monster. This confirms that you're a fiend from the lowest depths!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I can date whoever I want. I could date Asterius if he felt like it." },
				{ Emote = "PortraitEmoteAnger", Text = "How dare you lay claim to my Asterius in that way! He has no desire to even speak with you, let alone enter into some sort of relationship!"},
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Someone's not jealous at all. Let's take out our frustrations on the battlefield, king." },
			},
			TheseusAboutMegAlt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutMegAlt",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredAnyTextLines = { "BecameCloseWithMegaera01_BMeg_GoToHer", "BecameCloseWithMegaera01Meg_GoToHer" },
				RequiredFalseTextLines = {"TheseusGift06", "TheseusAboutMeg"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Blackguard, you're consorting with a fury?"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Who, Meg? Possibly. We used to be together so this isn't a new thing." },
				{ Text = "You have even poorer judgement than I expected, monster. This confirms that you're a fiend from the lowest depths!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I can date whoever I want. Who are you to judge?" },
				{ Emote = "PortraitEmoteAnger", Text = "I have every right to judge you! I'm a king and you're just a monster."},
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Let's finish this conversation on the battlefield, king." },
			},

			TheseusAboutMegAndThan =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutMegAndThan",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredAnyTextLines = { "TheseusAboutMeg", "TheseusAboutMegAlt" },
				RequiredTextLines = {"TheseusAboutThan", "TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Zagreus, other shades have told tales of the prince of the Underworld dating not just one but two others. Is this true?"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "It is. Gods aren't as worried about monogamy as I've heard mortals can be." },
				{ Text = "I apologize for being so cruel to you when I first heard of your relationships." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "You were cruel to me pretty much constantly back then. We've moved past that now." },
				{ Emote = "PortraitEmoteAffection", Text = "The forgiveness of a god is truly an unbelievable thing to behold!"},
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Seriously, it feels weird when you call me a god. Just treat me like normal, minus the angry yelling. You can even call me a daemon again for all I care. Just not a god." },
				{Text = "It feels sacrilegious to do so... daemon."},
			},
			TheseusAboutMegAndThanAlt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutMegAndThanAlt",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredAnyTextLines = { "BecameCloseWithMegaera01_BMeg_GoToHer", "BecameCloseWithMegaera01Meg_GoToHer" },
				RequiredAnyTextLines = { "BecameCloseWithThanatos01Than_GoToHim", "BecameCloseWithThanatos01_BThan_GoToHim" },
				RequiredTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Zagreus, other shades have told tales of the prince of the Underworld dating not just one but two others. Is this true?"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "It is. Gods aren't as worried about monogamy as I've heard mortals can be." },
				{ Text = "How wonderful to hear that you've found love with multiple others! The lives of the gods are truly glorious to behold." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Seriously, it feels weird when you call me a god. Just treat me like normal, minus the angry yelling. You can even call me a daemon again for all I care." },
				{Text = "It feels sacrilegious to do so... daemon."},
			},
			TheseusAboutAchilles =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutAchilles",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredAnyTextLines = { "AchillesFirstMeeting", "AchillesFirstMeeting_Alt" },
				RequiredTextLines = {"TheseusGift08", "TheseusHasWeaponUpgrade01"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "King, I've asked you this once before, but it was in front of an audience so you didn't give an honest response. Have you ever known Achilles?" },
				{ AngleTowardHero = true, Text = "Achilles? Ah, that hero who was after my time. Shades in Elysium often speak of him! Why do you ask?" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "Just idle curiousity, really. Elysium is filled with so many legends that I wondered if one like him stood out above the rest." },
				{ Text = "There are legends among legends, Prince. I may be one of many shades here, for instance, but no other can claim the title of Champion of Elysium!"},
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "True, you certainly stand out as well." },
			},
			TheseusAboutCharon =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutCharon",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "CharonGift03", "TheseusGift06" },
				RequiredSeenRooms = { "D_Hub" },
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus, I was just wondering, what sorts of goods do you and the other shades purchase from Charon? All he does is sell me boons, hearts, and hammers." },
				{ AngleTowardHero = true, Text = "I get my favors from the gods through prayer, not coin. Charon sells no boons to the rest of us. He offers weaponry, armor, building supplies, miscellaneous goods. Everything a shade could possibly need here!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Wow, that's a lot. I guess he knows I don't need that many options." },
			},

			TheseusAboutSkelly =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutSkelly",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredTextLines = { "SkellyGift01"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Not sure why I'm bothering to ask, but do you know anything about a skeleton who showed up in my courtyard?" },
				{ AngleTowardHero = true, Emote = "PortraitEmoteSurprise",
					Text = "As if I'd consort with fiendish monsters like you do, blackguard!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Guess not, then. Really not sure why I even asked you." },
			},
			TheseusAboutMyrmidonReunionQuestComplete01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutMyrmidonReunionQuestComplete01",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "MyrmidonReunionQuestComplete", "TheseusGift08" },
				MinRunsSinceAnyTextLines = { TextLines = { "MyrmidonReunionQuestComplete" }, Count = 4 },
				RequiredFalseTextLinesLastRun = { "MyrmidonReunionQuestComplete" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "The shade Patroclus told me recently that you reunited him with his long-lost lover." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Achilles? Yeah, I did. I had to break their pact with my father, but they get to spend eternity together now." },
				{ Text = "All of Elysium thanks you. He may have been the gloomiest shade here, yet he refused to drink enough from the river to forget his troubles! I never understood it." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Because he didn't want to forget. Would you drink to forget your father or son?" },
				{ Text = "No, never! I understand now, I believe. The memories may hurt, but they're all we have." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Exactly. But that's not true anymore for Patroclus and Achilles. They'll have each other from now on." },
			},


			TheseusAboutSingersReunionQuestComplete01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutSingersReunionQuestComplete01",
				PlayOnce = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				UseInitialInteractSetup = true,
				RequiredTextLines = { "OrpheusAboutSingersReunionQuest01" },
				RequiredFalseTextLines = {"TheseusGift06", "TheseusAboutSingersReunionQuestComplete01Alt"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Daemon! I've heard that a court singer was reunited with his muse due to a contract being broken?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "That's right. I broke his contract, rekindling their love. It was rather sweet, really." },
				{ Text = "I'd expect nothing less than for you to use your underhanded, daemonic ways to break a contract." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Emote = "PortraitEmoteSurprise",
					Text = "What? It was an unfair contract. You're just trying to yell at me for any reason you can think of." },
				{ Text = "Silence, daemon!" },
			},
			TheseusAboutSingersReunionQuestComplete01Alt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusAboutSingersReunionQuestComplete01Alt",
				PlayOnce = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				UseInitialInteractSetup = true,
				RequiredTextLines = { "OrpheusAboutSingersReunionQuest01", "TheseusGift06" },
				RequiredFalseTextLines = {"TheseusAboutSingersReunionQuestComplete01"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Zagreus! I've heard that a court singer was reunited with his muse due to a contract being broken?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "That's right. I broke his contract, rekindling their love. It was rather sweet, really." },
				{ Text = "How daring of you, going against Lord Hades himself! You're a legend among gods!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I don't know about that. I was just trying to help a friend. I'd do the same for you if necessary." },
				{ Text = "Let's hope that will never be the case." },
			},

			TheseusRunCleared =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusRunCleared",
				Priority = true,
				PlayOnce = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiresRunCleared = true,
				UseInitialInteractSetup = true,
				RequiredTextLines = { "PersephoneFirstMeeting" },
				RequiredFalseTextLines = { "Ending01", "TheseusGift06" },
				{ PreLineWait = 0.35, AngleTowardHero = true,
					Text = "Daemon! I've heard tell that you've managed to slay your own father. How despicable, yet I didn't expect any less from you!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Well he didn't give me much of a choice. And it's not like he didn't come back. Wait, did you just acknowledge that I'm the prince?" },
				{ Emote = "PortraitEmoteAnger", Text = "Absolutely not! Foul monster, you nearly convinced me to spout your lies!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Or you forgot to deny the truth for once. I'd go with the latter, personally. But yes, I killed him. And I'll kill you again in a minute too." },
			},


	
			TheseusNPCPostEnding01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusNPCPostEnding01",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredTextLines = { "Ending01", "TheseusFirstMeeting" },
				RequiredFalseTextLines = {"TheseusNPCPostEnding01_Alt", "TheseusGift06"},
				MaxRunsSinceAnyTextLines = { TextLines = { "Ending01" }, Count = 20 },

				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Blackguard, you look particularly happy today." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "I am. Something very good happened to me recently, and I'm quite happy about it." },
				{ Text = "Does this have anything to do with the rumors about the queen?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I couldn't say. Can you promise not to tell anyone but Asterius if I tell you the truth?" },
				{ 
					Text = "Of course you can. Have you ever met anyone more trustworthy or likeable than myself?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Yes. Fine, it's true that my mother returned. Believe it or not, she's the queen, and she's back. And even better, I get to keep fighting my way out of this place. It's my job now." },
				{ 
					Emote = "PortraitEmoteFiredUp",
					Text = "In that case, prepare to fight. I'll fight anyone who espouses such lies about the queen!" },
			},

			TheseusNPCPostEnding01_Alt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusNPCPostEnding01_Alt",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "Ending01", "TheseusGift06", "TheseusFirstMeeting" },
				RequiredFalseTextLines = {"TheseusNPCPostEnding01"},
				MaxRunsSinceAnyTextLines = { TextLines = { "Ending01" }, Count = 20 },

				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Is it true, Prince Zagreus? Your mother -- the queen -- has she returned to you?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "She has. It's a bit strange at the moment having her back, but I wouldn't trade it for anything." },
				{ 
					Text = "I've never seen you look this happy. I'm not sure how I ever mistook you for a daemon when you're clearly a god! Will you still come up to Elysium to visit?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Not just to visit. I'll be officially coming to Elysium to fight you so we can help ensure the realm stays secure." },
				{ 
					Text = "Ah, that's outstanding news! Although I can assure you that Elysium is perfectly secure, other than when you break out of it." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "So it's not that secure then?" },
				{ Text = "Hmph. Potentially there are a few flaws. But Asterius and I have been training intensely, and you won't be getting past us again!"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "We'll see about that, king." },
			},

			TheseusNPCPostEpilogue01_Alt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusNPCPostEpilogue01_Alt",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredTextLines = { "OlympianReunionQuestComplete", "TheseusGift06", "TheseusFirstMeeting" },
				RequiredFalseTextLines = {"TheseusNPCPostEpilogue01"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "{#DialogueItalicFormat}<Whistles>{#PreviousFormat}" },
				{  AngleTowardHero = true, Text = "You seem quite cheerful today, Prince Zagreus!"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Hi Theseus! I am. I've told the gods on Olympus the truth about my mother, and we're finally at peace." },
				{ Emote = "PortraitEmoteCheerful", Text = "Such glorious news, my friend! I'm so happy for you. Will you still be visiting us here?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", Text = "Yep, I'm still employed, so you'll see me around. I was planning to fight you and Asterius shortly."},
				{ Text = "Well, Asterius and I will be ready for you, in that case. And if you want to celebrate sometime with a bottle of ambrosia or two, just let me know. I can throw the grandest parties in Elysium!"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", Text = "Dionysus celebrated enough for all of us, so not today. I'd appreciate a good fight in the stadium, though."},
				{ Text = "A good fight you shall have!"},
			},

			TheseusNPCPostEpilogue01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusNPCPostEpilogue01",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredTextLines = { "OlympianReunionQuestComplete", "TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusNPCPostEpilogue01_Alt"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "{#DialogueItalicFormat}<Whistles>{#PreviousFormat}" },
				{ AngleTowardHero = true, Text = "Monster, how dare you whistle in the fields of Elysium!"},
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I didn't realize that wasn't allowed. My apologies, king." },
				{ Text = "You're forgiven, at least until we meet on the battlefield shortly. Why are you so happy, anyway?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Because I've told the gods on Olympus the truth about my mother, and we're finally at peace. Not that you'll believe a word of that." },
				{ Text = "You're correct, blackguard! Not a word. When I call upon the gods soon and destroy you, you'll see who's really at peace with them." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "That would be me. See you in a bit, Theseus." },
			}, 
			
			TheseusFraternalBondsAftermath_Alt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusFraternalBondsAftermath_Alt",
				SuperPriority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredAnyTextLines = { "TheseusAboutFraternalBonds06_A", "TheseusAboutFraternalBonds06_B" },
				RequiredTextLines = {"TheseusGift06", "TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusFraternalBondsAftermath"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "King, it's good to see you. I wanted to speak to you, if you're willing to talk." },
				{ AngleTowardHero = true, Text = "Of course I am, dearest friend!"},
				{ Emote = "PortraitEmoteSurprise", Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Wait, really? I was sure I'd upset you." },
				{ Text = "That was just a show for the shades. A brief spectacle Asterius and I decided to put on as a form of light entertainment! I'm not the least bit upset with you or Asterius." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", Text = "You put on a good act, that's for sure. But where have you been all this time?"},
				{ Text = "Asterius and I have been training quite intensely lately. Don't expect to get through us again, former daemon!"},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", Text = "We'll see about that, now won't we?"},
			},
			TheseusFraternalBondsAftermath =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusFraternalBondsAftermath",
				SuperPriority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredAnyTextLines = { "TheseusAboutFraternalBonds06_A", "TheseusAboutFraternalBonds06_B" },
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusFraternalBondsAftermath_Alt", "TheseusGift06"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus, I was wondering if we could talk." },
				{ AngleTowardHero = true, Text = "I have nothing to say to you, fiend! You tried to ruin my friendship with my dear Asterius!"},
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I did nothing of the sort! If you'd only listen to Asterius for a few seconds, you'd see he's telling the truth." },
				{ Emote = "PortraitEmoteSurprise", Text = "How dare you! No one listens to Asterius better than I. I'm the best listener in all of Elysium!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag", Text = "Do you even hear the words that come out of your mouth sometimes? If you'd listened to him, none of this would have happened."},
				{ Text = "I know not what you mean. Regardless, in one of my many displays of benevolence, I've decided to forgive you."},
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag", Text = "Wow, so generous of you. I'd forgive me if I'd done nothing wrong, too."},
				{ Text = "You're forgiven, daemon! I have nothing else to say to you."},
			},
			TheseusNPCExtremeMeasures =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusNPCExtremeMeasures",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredMinActiveMetaUpgradeLevel = { Name = "BossDifficultyShrineUpgrade", Count = 3 },
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusExtremeMeasures02"},
				RequiredFalseTextLines = {"TheseusGift06", "TheseusNPCExtremeMeasuresAlt"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Daemon! For once, I have to thank you! By entering the stadium, you'll soon give Asterius and I the opportunity to destroy you while encased in glorious armor!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Seriously, you do know I'm the reason you have that chariot, don't you? How did you get it?" },
				{ Text = "Lord Hades told me that, due to my excellence as Champion, Asterius and I have earned the honor of wearing this armor on certain occasions during our battles with you!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Father appealed to your ego instead of telling you the truth, then? In reality, I was getting through you easily enough that I asked for the armor to make our fights more difficult." },
				{ Emote = "PortraitEmoteAnger", Text = "That is simply untrue, daemon! Now, no more lies from you! I must change into my divine suit and prepare to expel this hellspawn from Elysium!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Have fun with that. And remember, it's all thanks to me!" },
			},
			TheseusNPCExtremeMeasuresAlt =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusNPCExtremeMeasuresAlt",
				Priority = true,
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredMinActiveMetaUpgradeLevel = { Name = "BossDifficultyShrineUpgrade", Count = 3 },
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusExtremeMeasures02", "TheseusGift06"},
				RequiredFalseTextLines = {"TheseusNPCExtremeMeasures"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Prince, soon we will do battle once again in the glorious armor I've been granted by Lord Hades!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "By Lord Hades? I wasn't kidding before. It was actually all due to a Pact of Punishment I've signed." },
				{ Text = "You're speaking the truth? So he lied when he said that it was due to my prowess on the battlefield?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I'm sure that contributed too. No one but you and Asterius gets to use it, right? So I wouldn't feel too down." },
				{ Text = "You're right. Of course you're right, friend! I never should have doubted myself. Regardless of the cause, I look forward to many more matches of skill between us, both armored and bare!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I do too, king." },
			},
			TheseusMiscChat01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscChat01",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				RequiredMoneyMax = 0,
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Ha! The daemon is bereft of both morals and funds!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "How do you even know how much gold I have?" },
				{ Text = "Fair Charon over there just commented on your impoverished nature. Are you so uneducated that his words are meaningless to you?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "{#DialogueItalicFormat}You {#PreviousFormat}of all people can understand Charon? I was under the impression that his words were meaningless to most." },
				{ Text = "Haha! The daemon's ignorance is clear yet again! Charon and I have had many wondrous conversations about topics a monster such as you would never comprehend." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I honestly can't tell if you're lying or telling the truth, not that I'd care either way." },
			},
			TheseusMiscChat02 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscChat02",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift01"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus." },
				{ AngleTowardHero = true, Text = "Spineless filth, I crushed a rock underfoot earlier on this day or night and imagined it was your skull!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Aw, how adorable that you were thinking of me. Am I often in your thoughts?" },
				{ Text = "Brainless scum! How dare you presume that I was thinking of you!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "I mean, did you not just say that you were? Makes me wonder which one of us is brainless." },
				{ Text = "It will be you, blackguard, once I remove your brain with my blessed spear!" },
			},
			TheseusMiscChat03 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscChat03",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift03"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Have you ever drunk from the river Lethe, Theseus?" },
				{ AngleTowardHero = true, Text = "What say you, blackguard? How dare you presume to ask such a personal question of the great Theseus?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Never mind then. Gods forbid I try to make pleasant conversation with you for once." },
				{ Text = "I have not." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Haven't what? Drunk from the river? Let me guess - you'd never want to forget the beauty of your glorious wins in battle? Something like that?" },
				{ Text = "Exactly right, for once. My memories of my life outshine those of all the other shades here. I have no need to forget a single one!" },
			},
			TheseusMiscChat04 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscChat04",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				GiftableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Blackguard, I'd like to extend a generous offer to you, as I am surely the kindest shade you've ever met." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Uh, if you say so. What's the offer?" },
				{ Text = "I'll permit you to enter the stadium as a member of the audience, so you can watch Asterius and I defeat others who would try to take my position as Champion!" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "Theseus, don't get offended by this, but I have little interest in seeing your battles with the other shades. However, a nice walk through Elysium and bottle of ambrosia would be lovely." },
				{ Emote = "PortraitEmoteAnger", Text = "I would never share my precious ambrosia with you, blackguard! Forget I offered. You clearly have no taste for the finer things in life or death." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Sorry. Like I said, didn't mean to offend." },
			},
			TheseusMiscChat05 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscChat05",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "PatroclusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06", "PatroclusWithAchilles01"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Monster, have you run into a shade during your travels through Elysium? One who just sits on the ground gloomily, refusing to engage in combat?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "A gloomy shade who just sits by the river? I know of him. Why?" },
				{ Text = "He frustrates me almost as much as you do! Thrice now I've attempted to regale him with tales of my glory, but he ignores me!" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "Do shades generally jump at the chance to hear those tales? Not sure why they would." },
				{ Text = "Well, you'd never understand, monster. Yes, shades love hearing them! Why, when I finish my last tale after a few hours of storytelling, their joy is unmistakable!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Hmm, wonder why!" },
			},
			TheseusMiscMaxChat01 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscMaxChat01",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift06"},
				RequiredFalseTextLines = { "TheseusAsteriusIntermission"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Hey mate, how are you and Asterius on this day or night?" },
				{ AngleTowardHero = true, Text = "Mate? We may be on more friendly terms now, Prince, but I must inform you that I do not desire to mate with you right now!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Nor do I at the moment, no worries there. It's just another word for friend." },
				{ Text = "Ah, of course! Mate! Well, mate, Asterius and I are doing beautifully! Elysium is as eternally perfect as ever. What about you, mate?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "You know, please never say that word again." },
				{ Text = "Of course, mate!" },
			},
			TheseusMiscMaxChat02 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscMaxChat02",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Hi Theseus! I was just curious, do you know the name of the shade who supports me?" },
				{ AngleTowardHero = true, Text = "I cannot say that I do, my dear friend! I know of whom you speak, as their banner used to rile me up, but I've never spoken with them." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "That's too bad! I was hoping to introduce myself." },
				{ Text = "I'll use my many connections here to identify them for you, Prince! Fear not, you shall know their name soon!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Thanks, Theseus. I'd appreciate it." },
			},
			TheseusMiscMaxChat03 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscMaxChat03",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08", "TheseusMiscMaxChat02"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus, just wanted to see if you'd had any luck figuring out who my good shade is." },
				{ AngleTowardHero = true, Text = "I have, Prince Zagreus! She's named Alice, and she said, quote, 'I'm a huge fan of his and I'm honored he wanted to know my name!', end quote." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Alice! That's good to know. She's been a fan of mine since the beginning." },
				{ Text = "Yes, it used to greatly bother me, back when I was plagued by self doubt! But now I realize that every other shade supports me, so you deserve one fan." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "True, you have more than enough support between Asterius and the audience. Thanks again for helping with that!" },
				{ Text = "It's the least I can do to serve the gods!" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Please don't call me a god. Just Prince or Zagreus is great." },
				{ Text = "Of course, my dear friend!" },
			},
			TheseusMiscMaxChat04 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscMaxChat04",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08"},
				{ PreLineWait = 0.35, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Have I been imagining things, or is the flora in Elysium a bit more vibrant than usual lately?" },
				{ AngleTowardHero = true, Text = "You are not imagining that in the slightest, my brother in arms! I have been spending my leisure hours gardening nonstop to make Elysium beautiful!" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "Well, it's paying off. I've really noticed the difference lately. Is it still helping you to have something other than combat to look forward to?" },
				{ Text = "Yes, more than you'd dare to believe! Even if I fall to you in battle, which is possible but unlikely, my plants are still there to welcome me afterwards! And they do not judge me, unlike my fellow shades." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "It sounds like it's really helping then! I'm glad to hear it." },
			},
			TheseusMiscMaxChat05 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscMaxChat05",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Blackguard, I mean Prince Zagreus, how are you?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "You know, it honestly doesn't bother me that much anymore if you call me names. It's more affectionate than annoying at this point." },
				{ Text = "Is that so? So if I referred to you as a foul, despicable ingrate you wouldn't be offended?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I mean, that's a bit offensive, which I think you well know. But I don't mind blackguard or daemon." },
				{ Text = "Now that I can be fully certain you are a god, it feels disrespectful to refer to you by such names. But it also feels wrong when I give you the respect of the other gods." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Seriously, don't worry about it. Call me a blackguard all you'd like, king." },
				{ Text = "I shall then, blackguard!" },
			},
			TheseusMiscMaxChat06 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscMaxChat06",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusGift08", "AsteriusGift08", "TheseusMiscMaxChat05"},
				MinRunsSinceAnyTextLines = { TextLines = { "TheseusMiscMaxChat07" }, Count = 10 },
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Blackguard! You're just who I wanted to see! I'm in need of your assistance." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "Sure thing, king. How can I help?" },
				{ Text = "Asterius and I have a date scheduled for this day or night, but I cannot decide on what to wear. Do you think a royal blue tunic or light blue tunic would better show off my body?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Honestly, I think Asterius is going to appreciate your body no matter what you wear. But I'd go for the light blue if I was you." },
				{ Text = "Wonderful! Light blue it is then." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Let me know how it goes!" },
			},
			TheseusMiscMaxChat07 =
			{
				StatusAnimation = "StatusIconWantsToTalk",
				Name = "TheseusMiscMaxChat07",
				PlayOnce = true,
				UseInitialInteractSetup = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusGift08", "AsteriusGift08"},
				MinRunsSinceAnyTextLines = { TextLines = { "AsteriusMiscMaxChat02" }, Count = 10 },
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "My friend, would you do me the honor of choosing a drink for the fine meal I have planned for Asterius?" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "Sure, what are the options?" },
				{ Text = "I've decided to present him with either nectar or ambrosia!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Funnily enough, he asked me the same question a while ago. Let's mix it up. Why don't you offer him nectar? You both get a lot of ambrosia." },
				{ Text = "Excellent point! A partner as special to me as my dear Asterius deserves an interesting drink, and we drink ambrosia regularly. Nectar it is, then!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Hope the date goes well!" },
			},

			-- intermission scenes
			TheseusAsteriusIntermission = {
				Name = "TheseusAsteriusIntermission",
				PlayOnce = true,
				Priority = true,
				UseableOffSource = true,
				StatusAnimation = "StatusIconWantsToSmooch",
				GiftableOffSource = true,
				RequiredTextLines = {"TheseusGift08", "AsteriusGift08"},
				{ PreLineWait = 0.35, AngleTowardTargetId = 517230, Emote = "PortraitEmoteAffection", Text = "My precious Asterius, I love you dearly. You make my eternal existence worthwhile." },
				{ Speaker = "NPC_Asterius_01", Portrait = "Portrait_Minotaur_Default_01", Text = "I feel the same way, my king. I'd like to bed you now."},
				{ Text = "Let's make haste to my bedchambers immediately then! Prince, would you be interested in joining us? Asterius and I have realized that we're both attracted to you."},
				{ Text = "TA_ChoiceText01",
					Choices =
					{
						{ ChoiceText = "TA_BeWithThem",
							{ PostLineThreadedFunctionName = "LoungeRevelryPresentation", PostLineFunctionArgs = { Sound = "/VO/Minotaur_0183", Sound2 = "/VO/ZagreusHome_1516", Sound3 = "/VO/Theseus_0303" }, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", Text = "There's nothing I want more right now."},
							{ FadeOutTime = 0.5, FullFadeTime = 7.8, FadeInTime = 2.0, InterSceneWaitTime = 0.5, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", Text = "Wow. Can't say I've ever been with a minotaur before. That was incredible."},
							{ AngleTowardHero = true, Text = "Or I a daemon. Well, a prince, I mean. I enjoyed that immensely, Prince."},
							{ Speaker = "NPC_Asterius_01", Portrait = "Portrait_Minotaur_Default_01", Text = "I want to lay with you both again sometime."},
						},
						
						{
							ChoiceText = "TA_BackOff",
							{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
								PreLineAnim = "ZagreusTalkEmpathyStart", PreLineAnimTarget = "Hero",
								PostLineAnim = "ZagreusTalkEmpathy_Return", PostLineAnimTarget = "Hero",
								Text = "I'm sorry, but I'm not comfortable being with the both of you." },
							{ PreLineWait = 0.35, Text = "You're not? But who wouldn't be attracted to this glorious body? And my beautiful Asterius?" },
							{ Portrait = "Portrait_Minotaur_Default_01", Speaker = "NPC_Asterius_01", PreLineWait = 0.35, Text = "King, let him be. Let's go enjoy each other, then we can disembowel him once we return." },
							{ PostLineThreadedFunctionName = "LoungeRevelryPresentation", PostLineFunctionArgs = { Sound = "/VO/Minotaur_0183", Sound2 = "/VO/Theseus_0303", Sound3 = "/EmptyCue" }, Text = "What a wondrous idea, my darling bull!"},
							{ FadeOutTime = 0.5, FullFadeTime = 7.8, FadeInTime = 2.0, InterSceneWaitTime = 0.5, AngleTowardHero = true, Text = "I feel invigorated and ready for battle! We'll see you soon in the stadium, Prince!"},
						}
					},
				},

			},

		},

		
		RepeatableTextLineSets =
		{
			TheseusChat01 =
			{
				Name = "TheseusChat01",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "When we meet in the stadium in mere moments, daemon, I shall crush you!" },
			},
			TheseusChat02 =
			{
				Name = "TheseusChat02",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Emote = "PortraitEmoteAnger", Text = "Loathsome pustule, you have no right to purchase wares from Charon! Soon you shall be punished with my spear!" },
			},
			TheseusChat03 =
			{
				Name = "TheseusChat03",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "I have nothing more to say to you, despicable fiend. But soon we shall converse through battle, when I impale you with my glorious spear!" },
			},
			TheseusChat04 =
			{
				Name = "TheseusChat04",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Emote = "PortraitEmoteAnger", Text = "How dare you scorch the grounds of fair Elysium with your burning, monstrous appendages, fiend! I have no wish to engage in dialogue with one such as yourself." },
			},
			TheseusChat05 =
			{
				Name = "TheseusChat05",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "You should know one thing and one thing only, blackguard! That's that I will vanquish you soon in front of my adoring audience!" },
			},
			TheseusChat06 =
			{
				Name = "TheseusChat06",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "These shades queueing to enter the stadium care not for you, fiend! They come to watch me and Asterius alone." },
			},
			TheseusChat07 =
			{
				Name = "TheseusChat07",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "As Champion of Elysium, I'll graciously permit you the honor of engaging with Asterius and I in combat today. You should be grateful, fiend!" },
			},
			TheseusChat08 =
			{
				Name = "TheseusChat08",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				RequiredMaxHealthFraction = 0.25,
				RequiredMaxLastStands = 0,
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Fiend, you are in no fit state to fight Asterius and I! Buy some food from Charon to replenish your health before I disembowel you in mere moments." },
			},
			TheseusChat09 =
			{
				Name = "TheseusChat09",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Asterius, could there be a daemon in front of us attempting to speak with me? No, it must have been a trick of the light." },
			},
			TheseusChat10 =
			{
				Name = "TheseusChat10",
				UseableOffSource = true,
				RequiredTextLines = {"TheseusFirstMeeting"},
				RequiredFalseTextLines = {"TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Daemon, I have no desire to speak with you prior to our battle. Prepare yourself, as you will soon be sent back to the depths from whence you came!" },
			},


			-- max relationship

			TheseusMaxChat01 =
			{
				Name = "TheseusMaxChat01",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "One whom I formerly referred to as daemon, please avail yourself of Charon's wares so that we may soon face each other in combat!" },
			},
			TheseusMaxChat02 =
			{
				Name = "TheseusMaxChat02",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift06"},
				RequiredMoneyMax = 0,
				{ PostLineThreadedFunctionName = "TheseusGiveMoney", PreLineWait = 0.35, AngleTowardHero = true, Text = "One should not walk around Elysium with a coin purse as bare as yours, Prince. Have some gold!" },
			},
			TheseusMaxChat03 =
			{
				Name = "TheseusMaxChat03",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Prince Zagreus, Asterius and I have been training fiercely. This next match will be a great one!" },
			},
			TheseusMaxChat04 =
			{
				Name = "TheseusMaxChat04",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Approach the stadium when you're ready, compatriot. Asterius and I await you!" },
			},
			TheseusMaxChat05 =
			{
				Name = "TheseusMaxChat05",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift06"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "I take no pleasure nowadays in slaying you, Prince, but nothing pleases me more than the joy of combat!" },
			},
			TheseusMaxChat06 =
			{
				Name = "TheseusMaxChat06",
				PlayOnce = true,
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08"},
				RequiredMoneyMax = 50,
				{ PostLineThreadedFunctionName = "TheseusGiveMoney", PreLineWait = 0.35, AngleTowardHero = true,
				Text = "Prince, you have almost no funds left! Let me provide you with some of the many splendors of Elysium in exchange for all that you've done for me!" },
			},
			TheseusMaxChat07 =
			{
				Name = "TheseusMaxChat07",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "I've been working in the garden again, Prince, nourishing the beauty of Elysium! The azaleas are coming along quite nicely." },
			},
			TheseusMaxChat08 =
			{
				Name = "TheseusMaxChat08",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "It's glorious to see you again, Prince Zagreus! I eagerly anticipate our upcoming match." },
			},
			TheseusMaxChat09 =
			{
				Name = "TheseusMaxChat09",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Never again will I let vile thoughts of my inadequacy penetrate my mind, thanks to you!" },
			},
			TheseusMaxChat10 =
			{
				Name = "TheseusMaxChat10",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Soon we will meet as brothers on the field of battle, and it shall be a glorious occasion!" },
			},
			TheseusMaxChat11 =
			{
				Name = "TheseusMaxChat11",
				UseableOffSource = true,
				RequiredTextLines = { "TheseusFirstMeeting", "TheseusGift08", "AsteriusRomanceQuest05"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "If it were not for you, my dear Zagreus, I would never have known the depth of Asterius's feelings for me. I am most grateful!" },
			},

			TheseusAsteriusIntermission02 = {
				Name = "TheseusAsteriusIntermission02",
				UseableOffSource = true,
				StatusAnimation = "StatusIconWantsToSmooch",
				GiftableOffSource = true,
				MinRunsSinceAnyTextLines = { TextLines = { "TheseusAsteriusIntermission", "TheseusAsteriusIntermission03" }, Count = 10 },
				RequiredTextLines = {"TheseusGift08", "AsteriusGift08", "TheseusAsteriusIntermissionTA_BeWithThem"},
				{ PreLineWait = 0.35, AngleTowardHero = true, Emote = "PortraitEmoteAffection", Text = "Zagreus, Asterius and I were wondering if you'd like to spend some time with us in our chambers before our fight!" },
				{ Speaker = "NPC_Asterius_01", Portrait = "Portrait_Minotaur_Default_01", Text = "We want to bed you, short one."},
				{ PostLineThreadedFunctionName = "LoungeRevelryPresentation", PostLineFunctionArgs = { Sound = "/VO/Minotaur_0183", Sound2 = "/VO/ZagreusHome_1516", Sound3 = "/VO/Theseus_0303" }, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", Text = "Gods, yes. Let's go there now."},
				{ FadeOutTime = 0.5, FullFadeTime = 7.8, FadeInTime = 2.0, InterSceneWaitTime = 0.5, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag", Text = "I feel like I could win against a thousand champions after that."},
				{ Text = "We'll see if those feelings are correct shortly, dearest Prince!"},
			},

		}, 

		GiftTextLineSets =
		{
			TheseusGift01 =
			{
				Name = "TheseusGift01",
				PlayOnce = true,
				RequiredKills = { Theseus = 5},
				{ PreLineWait = 0.35, AngleTowardHero = true, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus. Not sure why, but I wanted you to have this. As much as it pains me to say it, I've been enjoying our matches." },
				{ 	Text = "What is this, daemon? Is it poisoned? Are you trying to ruin the sanctity of combat with your underhanded daemonic strategies?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "What? What would even be the point when you'd just regenerate immediately? Hasn't anyone ever just done something nice for you?" },
				{	Text = "Yes, frequently. My subjects regularly pledged their loyalty to me when I was their beloved king."},
				{Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Of course they did. They were your subjects. I'm not. I meant, has anyone just done something nice for you when it wouldn't benefit them in return?" },
				{ Text = "Regularly, daemon. Asterius frequently gives me backrubs after we soundly defeat our combatants in our matches."},
				{Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "You know what? Forget I asked." },
				{ Text = "Gladly."},
				{ Text = "Wait, daemon!"},
				{Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "What?" },
				{ Text = "I've decided I'll offer you this in return. Consider yourself repaid in full for the act of generosity. Now, we must prepare for our battle."},

			},
			TheseusGift02 =
			{
				Name = "TheseusGift02",
				PlayOnce = true,
				RequiredTextLines = { "TheseusGift01" },
				
				{PreLineWait = 0.35, AngleTowardHero = true, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I picked up some extra nectar and thought you might like some, so here." },
				{ Text = "I don't need nectar from a foul, loathsome, evil little cockroach such as yourself!" },
				{Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Nevermind, then. I'll just take it back." },
				{ Text = "On second thought, I'll keep it! A monster such as you has no need for a delicacy like this anyway." },
				{Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Whatever you say, Theseus. Hope you enjoy the nectar." },
				{ Text = "I will be pouring it out in the river as soon as you're out of sight, daemon. Ready yourself for our battle and your inevitable defeat!" },
			},
			TheseusGift03 =
			{
				Name = "TheseusGift03",
				PlayOnce = true,
				RequiredTextLines = { "TheseusGift02" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
				Text = "Here's some more nectar for you to dump in the river, Theseus." },
				{Text = "Ah, daemon. You've returned to besmirch the fields of fair Elysium again!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "If you don't mind me asking, not that I care if you do mind, why do you act like this?" },
				{Text = "Act like what, daemon? Acting is a dishonorable profession." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
				Text = "Act like such a blowhard. You can't honestly be like this all the time. Is it just putting on a front for your audience?" },
				{Text = "I haven't the faintest idea what you mean, fiend."},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
				Text = "Or are you doing it for me? Because you should know you don't need to act like this. I'd much rather see the real you." },
				{Text = "Leave me be, daemon! I'm warning you. I have nothing else to say to you."},
			},
			TheseusGift04 =
			{
				Name = "TheseusGift04",
				PlayOnce = true,
				RequiredTextLines = { "TheseusGift03" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Text = "Daemon! You were right earlier." },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Wait, what? Right about what? Oh, here's some nectar." },				
				{ Text = "You don't remember our earlier conversation?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Sorry, I can't say I do. You mean our conversation on the battlefield?" },
				{ Text = "No, we spoke here. But regardless, if you cannot even bother to recall our discussion, then it was of no importance." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Sorry, Theseus. I wish I could remember. Can you give me a hint?" },
				{ Text = "You're speaking nonsense, fiend. Go now. We have a battle to fight soon." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I'll try to remember, Theseus. It seems like it was important to you." },
			},

			TheseusGift05 =
			{
				Name = "TheseusGift05",
				PlayOnce = true,
				RequiredTextLines = { "TheseusGift04" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus, I remember now! I also found you this nectar." },
				{ Text = "Remember what, despicable fiend?" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "About our conversation. I asked if you acted like this because you were putting on a front, and you said I was right." },
				{ Text = "Hmph. That may potentially be correct, daemon. What of it?" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "You don't need to do this - insult me, pretend to be so high and mighty, put on a front - any of it." },
				{ Text = "You say that, daemon, but it's the only way those here will respect me. I'm the great King Theseus!" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "Maybe so, but you're also a shade now. This is a place of eternal rest and prosperity, and you're one of my subjects. You deserve the chance to be yourself." },
				{ Text = "I wish I could rest, daemon. But I can't, not as long as I shall eternally live. This is who I have to be. It's who I am!" },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "I promise that's not true. Let me help you." },
				{ Text = "I'm not worth your help, fiend. I see your sense of judgement is as poor as your skill in the martial ways. I must go now to prepare for combat." },
			},
			TheseusGift06 =
			{
				Name = "TheseusGift06",
				PlayOnce = true,
				RequiredTextLines = { "TheseusGift05" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I found this nectar for you, Theseus. Would you like it?" },
				{ Text = "Sure, fiend. I suppose I can trust you not to have poisoned it." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "I wouldn't poison you. I wanted to offer to help you again, actually, in case you've reconsidered." },
				{ Text = "Why would you bother assisting me? I haven't exactly been kind to you." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Oh, I've noticed, trust me. I could have been nicer to you in return. But I'd like to think that that wasn't the true you." },
				{ Text = "You have more faith in me than I have in myself, daemon... Fiend... What's your true name?" },
				{ Portrait = "Portrait_Zag_Defiant_01", Speaker = "CharProtag",
					Text = "Do you really not know it? I'm Zagreus. Or Prince Zagreus, since you seem like the formal type." },
				{ Text = "Prince Zagreus, then. If you think I'm deserving of your assistance, then I'll be a benevolent king and give you the opportunity to try." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "You are. And I do think that." },
				{ Text = "You truly are a god, aren't you?" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I truly am. But honestly, I sort of liked our previous dynamic. Don't feel like you have to treat me like one." },
				{ Text = "It feels wrong to worship you when I regularly slay you on the battlefield. I'm not sure that I could treat you like a god if I tried. Plus, it would confuse the shades. I'll act the same with you in combat as always." },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Good. I'll see you shortly, then." },
			},

			-- high relationship / locked gifts
			TheseusGift07 =
			{
				Name = "TheseusGift07",
				PlayOnce = true,
				RequiredTextLines = { "TheseusInsecurityQuest05" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus, I know it's not much since we win it in our matches all the time, but I wanted to give you this." },
				{ Emote = "PortraitEmoteSurprise", Text = "Ambrosia? Why, that's quite gracious of you, Prince Zagreus! I appreciate the gift regardless of how often I receive it. You are a dear friend of mine, and I don't have many of those." },
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag",
					Text = "I consider you a good friend too. See you on the battlefield?" },
				{ Text = "I look forward to it." },
			},

			TheseusGift08 =
			{
				Name = "TheseusGift08",
				PlayOnce = true,
				RequiredTextLines = { "TheseusGift07" },
				{ PreLineWait = 0.35, AngleTowardHero = true, Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Theseus, it seems a bit ridiculous to keep giving you these, but I thought you might like another bottle." },
				{ Emote = "PortraitEmoteAffection", Text = "More ambrosia? That's not ridiculous at all, my dear friend!" },
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "Would you like to share it now in your chambers before the match begins?" },

				{ PostLineThreadedFunctionName = "LoungeRevelryPresentation", PostLineFunctionArgs = { Sound2 = "/EmptyCue", Sound3 = "/EmptyCue" }, Text = "There's nothing I would love more!"},

				{ FadeOutTime = 0.5, FullFadeTime = 7.8, FadeInTime = 2.0, InterSceneWaitTime = 0.5, Text = "And that's what became of my family."},
				{Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag", Text = "I'm so sorry about your father and son, Theseus."},
				{ Text = "Perhaps now you can see why I'm the kind of man I am. I was a good king, but led a tragic life. It affects me still."},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I can't imagine dealing with all of that. Have you ever thought about seeking them out?" },
				{ Text = "I can't say I have. Perhaps I will, some day or night. When I'm ready."},
				{ Portrait = "Portrait_Zag_Default_01", Speaker = "CharProtag",
					Text = "I'd be nervous too. I felt similarly when I first decided to seek my mother. It was worth it though, in the end." },
				{ Text = "Have I ever said how grateful I am that I can call you a friend now? I wanted to befriend you when we first met, but I never would have said it."},
				{ Portrait = "Portrait_Zag_Empathetic_01", Speaker = "CharProtag", Emote = "PortraitEmoteSurprise", Text = "Wait, seriously? So all that blustering and shouting was you trying to be my friend? Honestly, I never would have guessed."},
				{ Text = "I suppose I could have been more direct. Regardless, I'm glad that we're friends now. I look forward to many more conversations, drinks, and fierce battles to the death together!"},
				{ Emote = "PortraitEmoteAffection", Portrait = "Portrait_Zag_Default_01",
					PostLineThreadedFunctionName = "MaxedRelationshipPresentation",
					PostLineFunctionArgs = { Text = "NPC_Theseus_01", Icon = "Keepsake_TheseusSticker_Max" },  Text = "I do too, king."},
			},

		},


		GiftGivenVoiceLines =
		{
			{
				BreakIfPlayed = true,
				PreLineWait = 1.0,
				PlayFromTarget = true,

				-- I, uh, thanks.
				{ Cue = "/VO/ZagreusHome_0317" },
			},
		},
	}
    
ModUtil.Path.Wrap( "BeginOpeningCodex", 
	function(baseFunc)		
		if (not CanOpenCodex()) and IsSuperValid() then
			BuildSuperMeter(CurrentRun, 50)
		end
		ActivateRotatingNPCs({},{Types={"NPC_Theseus_01"}})
		--ForceNextRoomFunc("A_Makaria01")
		--local challengeBaseIds = GetIdsByType({ Name = "NPC_Makaria_01" })
		--GameState.Gift["NPC_Moros_01"] = nil
	    ModUtil.Hades.PrintStackChunks(ModUtil.ToString(GameState.Gift["NPC_Theseus_01"])) 
		baseFunc()
	end
)